name: project_2  # Change to your preferred environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - ipython
  - jupyter
  - scikit-learn
  - seaborn
  - pip
  - pip:
      - duckdb
