version: 2

models:
  - name: dim_customer
    description: "Dimension table for customers."
    columns:
      - name: customer_id
        description: "Natural key for the customer"
        tests:
          - not_null    # Ensures no null customer_id values
          - unique      # Ensures each customer_id is unique
      - name: customer_unique_id
        tests:
          - not_null

models:
  - name: fact_sales
    description: "Fact table capturing sales transactions."
    columns:
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_id